[project]
name = "esgf-magic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "intake-esgf>=2025.7.16",
    "pandas>=2.3.2",
]
